use_frameworks!

platform :ios, '8.0'

target 'KLHomeServiceInterface_Example' do
  pod 'KLHomeServiceInterface', :path => '../'

  target 'KLHomeServiceInterface_Tests' do
    inherit! :search_paths

    
  end
end
